/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8ZlhNnwkgVl
 */
import Link from "next/link";
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";
import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table,
} from "@/components/ui/table";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Button } from "@/components/ui/button";

export function Products() {
  return (
    <div className="flex flex-col min-h-screen">
      <main className="flex-1 p-4 md:p-6 lg:p-8">
        <div className="flex flex-col gap-4 md:gap-8">
          <Card>
            <CardHeader>
              <CardTitle>Products</CardTitle>
              <CardDescription>View and manage products</CardDescription>
            </CardHeader>
            <CardContent className="overflow-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Name</TableHead>
                    <TableHead>Quantity</TableHead>
                    <TableHead>Price</TableHead>
                    <TableHead>Status</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>Acme Shoes</TableCell>
                    <TableCell>100</TableCell>
                    <TableCell>$25.00</TableCell>
                    <TableCell>In Stock</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>Dynamic Headphones</TableCell>
                    <TableCell>50</TableCell>
                    <TableCell>$50.00</TableCell>
                    <TableCell>In Stock</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>Pro Camera</TableCell>
                    <TableCell>25</TableCell>
                    <TableCell>$300.00</TableCell>
                    <TableCell>In Stock</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>Mobile Charger</TableCell>
                    <TableCell>200</TableCell>
                    <TableCell>$10.00</TableCell>
                    <TableCell>In Stock</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>Designer Watch</TableCell>
                    <TableCell>10</TableCell>
                    <TableCell>$500.00</TableCell>
                    <TableCell>In Stock</TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Add Product</CardTitle>
              <CardDescription>Enter product details</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 gap-4">
                <div className="flex flex-col gap-1">
                  <Label htmlFor="name">Name</Label>
                  <Input id="name" placeholder="Enter name" />
                </div>
                <div className="flex flex-col gap-1">
                  <Label htmlFor="quantity">Quantity</Label>
                  <Input id="quantity" placeholder="Enter quantity" />
                </div>
                <div className="flex flex-col gap-1">
                  <Label htmlFor="price">Price</Label>
                  <Input id="price" placeholder="Enter price" />
                </div>
                <div className="flex flex-col gap-1">
                  <Label htmlFor="status">Status</Label>
                  <Select>
                    <option>In Stock</option>
                    <option>Out of Stock</option>
                    <option>In Transit</option>
                  </Select>
                </div>
              </div>
              <Button className="mt-4">Add Product</Button>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  );
}

function Package2Icon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>
  );
}
